/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vault;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author akku
 */

public class Password extends javax.swing.JFrame {
    int password[][]= new int[10][2];
    int repass[][]= new int[10][2];
    static int i=0,j=0;
    ImageIcon icon;
    /**
     * Creates new form NewJFrame
     */
    public Password() {
        initComponents();
        note.setVisible(false);
        jButton2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        note = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        warning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Choose an Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        note.setText("*Note: Select a minimum of 5 points on the image and remember it as password.");

        jButton2.setText("Reconfirm Password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(note)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(warning, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(note)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warning, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        JFileChooser jfc= new JFileChooser();
         FileFilter imgfilter = new FileNameExtensionFilter(
        "Image files", ImageIO.getReaderFileSuffixes());
        jfc.showOpenDialog(this);
        File f=jfc.getSelectedFile();
        String imgpath= f.getAbsolutePath();
        
        BufferedImage bi = null;
        try {
        bi = ImageIO.read(f);
        } catch (IOException e) {
            System.out.println("No image selected! ");
        //e.printStackTrace();
        }           
         icon = new ImageIcon(bi.getScaledInstance(label1.getWidth(), 
                label1.getHeight(), BufferedImage.SCALE_SMOOTH)); 
        //JLabel label1 = new JLabel(); 
        label1.setIcon(icon);
        label1.setVisible(true);
        note.setVisible(true); 
         label1.setOpaque(false); 
         label1.addMouseListener(new MouseAdapter() 
         {  
             @Override
            public void mouseClicked(MouseEvent e ) throws ArrayIndexOutOfBoundsException
         {   try{
             System.out.println("mouseClicked");
             
             password[j][0]=e.getX();
             password[j][1]=e.getY();
             System.out.println(password[j][0]+","+password[j][1]);
             Graphics g = label1.getGraphics();
             g.setColor(Color.red); //Setting color to red
             g.fillOval(password[j][0], password[j][1], 10, 10); //Drawing the circle/point
             g.drawString(Integer.toString(j+1), password[j][0], password[j][1] );
             g.dispose();
             j++;
            }
             
             catch(ArrayIndexOutOfBoundsException ae)
             {  warning.setText("You have exceeded Password limit!"); 
                warning.setVisible(true);
                jButton2.setVisible(false);
             }
             if(password.length > 5)
             {     
                 jButton2.setVisible(true);
                 
             }
             
         } 
         });
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         jButton1.setVisible(false);
         note.setVisible(false);
         warning.setVisible(false);
        label1.addMouseListener(new MouseAdapter() 
         {  
            public void mouseClicked(MouseEvent e1) throws ArrayIndexOutOfBoundsException
         {   try{
             
             
             repass[i][0]=e1.getX();
             repass[i][1]=e1.getY();
             if((repass[i][0]<(password[j][0])+10 && repass[i][0]>(password[j][0])-10 ||repass[i][0]==(password[j][0])&& (repass[i][1]<(password[j][1])+10 && repass[i][1]>(password[j][1])-10 ||repass[i][1]==(password[j][1]))))
             System.out.println(repass[i][0]+","+repass[i][1]);
             
             i++;
            }
             
             catch(ArrayIndexOutOfBoundsException ae1)
             {  warning.setText("You have exceeded Password limit!"); 
                warning.setVisible(true);
                jButton2.setVisible(false);
             }
             if(repass.length > 5)
             {     
                 jButton2.setVisible(true);
                 
             }
             
             
         }
         });
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Password().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel note;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
